In [0]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.datasets import mnist
from keras.models import Sequential,model_from_json
from keras.layers import Dense #each is connected to each other
from keras.optimizers import RMSprop
import pylab as plt

Using TensorFlow backend.


In [0]:
import pandas as pd
import numpy as np

In [0]:

from google.colab import files
uploaded = files.upload()

Saving dengue_features_test.csv to dengue_features_test (1).csv
Saving dengue_features_train.csv to dengue_features_train (1).csv
Saving dengue_labels_train.csv to dengue_labels_train (1).csv


In [0]:
 import io
df2 = pd.read_csv(io.BytesIO(uploaded['dengue_features_train.csv']))

In [0]:
df3=pd.read_csv(io.BytesIO(uploaded['dengue_labels_train.csv']))

In [0]:
df4=pd.read_csv(io.BytesIO(uploaded['dengue_features_test.csv']))

In [0]:
del df2['week_start_date']

In [0]:
del df4['week_start_date']

In [0]:
df2


city  year  ...  station_min_temp_c  station_precip_mm
0      sj  1990  ...                20.0               16.0
1      sj  1990  ...                22.2                8.6
2      sj  1990  ...                22.8               41.4
3      sj  1990  ...                23.3                4.0
4      sj  1990  ...                23.9                5.8
5      sj  1990  ...                23.9               39.1
6      sj  1990  ...                23.3               29.7
7      sj  1990  ...                22.8               21.1
8      sj  1990  ...                22.8               21.1
9      sj  1990  ...                24.4                1.1
10     sj  1990  ...                21.7               63.7
11     sj  1990  ...                23.9               12.2
12     sj  1990  ...                22.8               32.6
13     sj  1990  ...                22.8               37.6
14     sj  1990  ...                23.3               11.4
15     sj  1990  ...                22.8               44.7
16     sj  1990  ...                23.3                5.4
17     sj  1990  ...                24.4               13.7
18     sj  1990  ...                23.3               14.2
19     sj  1990  ...                24.4               25.9
20     sj  1990  ...                23.9                3.3
21     sj  1990  ...                24.4               15.8
22     sj  1990  ...                23.9               11.7
23     sj  1990  ...                24.4               57.7
24     sj  1990  ...                23.3               61.8
25     sj  1990  ...                21.7               91.5
26     sj  1990  ...                22.8                6.3
27     sj  1990  ...                23.9                6.6
28     sj  1990  ...                22.2               38.9
29     sj  1990  ...                22.2                9.6
...   ...   ...  ...                 ...                ...
1426   iq  2009  ...                22.2               49.0
1427   iq  2009  ...                21.2               41.9
1428   iq  2009  ...                22.0               54.1
1429   iq  2009  ...                21.8               31.2
1430   iq  2010  ...                 NaN                NaN
1431   iq  2010  ...                21.8                NaN
1432   iq  2010  ...                22.1               15.0
1433   iq  2010  ...                22.5                0.8
1434   iq  2010  ...                22.4              166.0
1435   iq  2010  ...                22.0               62.3
1436   iq  2010  ...                22.9               14.5
1437   iq  2010  ...                21.4               60.9
1438   iq  2010  ...                21.4               29.9
1439   iq  2010  ...                21.2                9.9
1440   iq  2010  ...                21.4               44.5
1441   iq  2010  ...                22.0               22.9
1442   iq  2010  ...                21.0               20.0
1443   iq  2010  ...                21.0               16.0
1444   iq  2010  ...                22.5                NaN
1445   iq  2010  ...                21.2               18.0
1446   iq  2010  ...                22.5               51.1
1447   iq  2010  ...                21.4               35.4
1448   iq  2010  ...                21.4                8.1
1449   iq  2010  ...                21.2               32.0
1450   iq  2010  ...                20.0                2.5
1451   iq  2010  ...                22.4               27.0
1452   iq  2010  ...                21.7               36.6
1453   iq  2010  ...                19.2                7.4
1454   iq  2010  ...                21.0               16.0
1455   iq  2010  ...                22.2               20.4

[1456 rows x 23 columns]

In [0]:
x_train=df2.iloc[:,:].values

In [0]:
y_train=df3.iloc[:,3].values

In [0]:
x_test=df4.iloc[:,:].values

In [0]:
x_train


array([['sj', 1990, 18, ..., 29.4, 20.0, 16.0],
       ['sj', 1990, 19, ..., 31.7, 22.2, 8.6],
       ['sj', 1990, 20, ..., 32.2, 22.8, 41.4],
       ...,
       ['iq', 2010, 23, ..., 32.2, 19.2, 7.4],
       ['iq', 2010, 24, ..., 31.2, 21.0, 16.0],
       ['iq', 2010, 25, ..., 33.7, 22.2, 20.4]], dtype=object)

In [0]:
y_train

array([4, 5, 4, ..., 1, 1, 4])

In [0]:
x_test

array([['sj', 2008, 18, ..., 33.3, 21.7, 75.2],
       ['sj', 2008, 19, ..., 30.0, 22.2, 34.3],
       ['sj', 2008, 20, ..., 32.8, 22.8, 3.0],
       ...,
       ['iq', 2013, 24, ..., 32.6, 21.6, 93.2],
       ['iq', 2013, 25, ..., 32.2, 21.8, 34.1],
       ['iq', 2013, 26, ..., 32.6, 22.0, 14.9]], dtype=object)

In [0]:
from sklearn.preprocessing import Imputer

In [0]:
imputer=Imputer()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
x_train[:,3:24]=imputer.fit_transform(x_train[:,3:24])

In [0]:
x_test[:,3:24]=imputer.fit_transform(x_test[:,3:24])

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
encoder=LabelEncoder()

In [0]:
x_train[:,0]=encoder.fit_transform(x_train[:,0])

In [0]:
x_train.shape

(1456, 23)

In [0]:
x_test[:,0]=encoder.fit_transform(x_test[:,0])

In [0]:
x_test.shape

(416, 23)

In [0]:
y_train

array([4, 5, 4, ..., 1, 1, 4])

In [0]:
batch=64

model=Sequential()
model.add(Dense(24, activation='sigmoid', input_shape=(23,)))
model.add(Dense(256, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='relu'))

model.summary()


Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 24)                576       
_________________________________________________________________
dense_2 (Dense)              (None, 128)               3200      
_________________________________________________________________
dense_3 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 257       
Total params: 37,057
Trainable params: 37,057
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='mean_absolute_error',
              optimizer='adam',
              metrics=['mae'])

In [0]:
history = model.fit(x_train,y_train,
                    batch_size=64,
                    epochs=250,
                    verbose=1)

Epoch 1/500
1456/1456 [==============================] - 0s 37us/step - loss: 18.1114 - mean_absolute_error: 18.1114
Epoch 2/500
1456/1456 [==============================] - 0s 35us/step - loss: 18.0737 - mean_absolute_error: 18.0737
Epoch 3/500
1456/1456 [==============================] - 0s 35us/step - loss: 18.0409 - mean_absolute_error: 18.0409
Epoch 4/500
1456/1456 [==============================] - 0s 35us/step - loss: 18.1663 - mean_absolute_error: 18.1663
Epoch 5/500
1456/1456 [==============================] - 0s 35us/step - loss: 18.1291 - mean_absolute_error: 18.1291
Epoch 6/500
1456/1456 [==============================] - 0s 36us/step - loss: 18.1227 - mean_absolute_error: 18.1227
Epoch 7/500
1456/1456 [==============================] - 0s 35us/step - loss: 18.0801 - mean_absolute_error: 18.0801
Epoch 8/500
1456/1456 [==============================] - 0s 37us/step - loss: 18.1526 - mean_absolute_error: 18.1526
Epoch 9/500
1456/1456 [==============================] - 0s 35us

In [0]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

NameError: ignored

In [0]:
 model.predict(x_test[0:4])

array([[7.825462],
       [7.935089],
       [7.823737],
       [7.836524]], dtype=float32)

In [0]:
y_train

array([4, 5, 4, ..., 1, 1, 4])

In [0]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [0]:
bestfeatures = SelectKBest(score_func='f_regression', k=15)
fit = bestfeatures.fit(x_train,x_test)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x_train.columns)
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(15,'Score'))  #print 10 best features

ValueError: ignored