In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
df = pd.read_csv("dengue_features_train.csv")

In [5]:
df

city  year  weekofyear week_start_date   ndvi_ne   ndvi_nw   ndvi_se  \
0      sj  1990          18      1990-04-30  0.122600  0.103725  0.198483   
1      sj  1990          19      1990-05-07  0.169900  0.142175  0.162357   
2      sj  1990          20      1990-05-14  0.032250  0.172967  0.157200   
3      sj  1990          21      1990-05-21  0.128633  0.245067  0.227557   
4      sj  1990          22      1990-05-28  0.196200  0.262200  0.251200   
5      sj  1990          23      1990-06-04       NaN  0.174850  0.254314   
6      sj  1990          24      1990-06-11  0.112900  0.092800  0.205071   
7      sj  1990          25      1990-06-18  0.072500  0.072500  0.151471   
8      sj  1990          26      1990-06-25  0.102450  0.146175  0.125571   
9      sj  1990          27      1990-07-02       NaN  0.121550  0.160683   
10     sj  1990          28      1990-07-09  0.192875  0.082350  0.191943   
11     sj  1990          29      1990-07-16  0.291600  0.211800  0.301200   
12     sj  1990          30      1990-07-23  0.150567  0.171700  0.226900   
13     sj  1990          31      1990-07-30       NaN  0.247150  0.379700   
14     sj  1990          32      1990-08-06       NaN  0.064333  0.164443   
15     sj  1990          33      1990-08-13       NaN  0.128033  0.206957   
16     sj  1990          34      1990-08-20  0.190233  0.168800  0.167657   
17     sj  1990          35      1990-08-27  0.252900  0.330750  0.264171   
18     sj  1990          36      1990-09-03  0.235400  0.200025  0.283817   
19     sj  1990          37      1990-09-10  0.127967  0.437100  0.123400   
20     sj  1990          38      1990-09-17  0.196350  0.182433  0.254829   
21     sj  1990          39      1990-09-24  0.116100  0.260900  0.199443   
22     sj  1990          40      1990-10-01  0.228550  0.189750  0.212486   
23     sj  1990          41      1990-10-08  0.171150  0.067550  0.179467   
24     sj  1990          42      1990-10-15       NaN  0.070200  0.181617   
25     sj  1990          43      1990-10-22  0.146200  0.089750  0.128829   
26     sj  1990          44      1990-10-29  0.252250  0.183433  0.318000   
27     sj  1990          45      1990-11-05  0.152600  0.181775  0.178329   
28     sj  1990          46      1990-11-12  0.290800  0.224600  0.180386   
29     sj  1990          47      1990-11-19  0.272200  0.330350  0.131633   
...   ...   ...         ...             ...       ...       ...       ...   
1426   iq  2009          49      2009-12-03  0.348529  0.290400  0.410614   
1427   iq  2009          50      2009-12-10  0.192200  0.193529  0.239886   
1428   iq  2009          51      2009-12-17  0.217600  0.240300  0.181771   
1429   iq  2009          52      2009-12-24  0.210422  0.257138  0.221133   
1430   iq  2010          53      2010-01-01       NaN       NaN       NaN   
1431   iq  2010           1      2010-01-08  0.124571  0.179129  0.163843   
1432   iq  2010           2      2010-01-15  0.145286  0.142314  0.135300   
1433   iq  2010           3      2010-01-22  0.252114  0.230486  0.187329   
1434   iq  2010           4      2010-01-29  0.263271  0.230600  0.218871   
1435   iq  2010           5      2010-02-05  0.170100  0.142117  0.117914   
1436   iq  2010           6      2010-02-12  0.230757  0.189257  0.163486   
1437   iq  2010           7      2010-02-19  0.293300  0.247829  0.206629   
1438   iq  2010           8      2010-02-26  0.303657  0.260057  0.225486   
1439   iq  2010           9      2010-03-05  0.127317  0.181160  0.120467   
1440   iq  2010          10      2010-03-12  0.311729  0.292686  0.272586   
1441   iq  2010          11      2010-03-19  0.294600  0.250971  0.281471   
1442   iq  2010          12      2010-03-26  0.266286  0.301233  0.296000   
1443   iq  2010          13      2010-04-02  0.141433  0.204729  0.250971   
1444   iq  2010          14      2010-04-09  0.242843  0.272757  0.202271   
1445   iq  2010          15      2010-04-16  0.157686  0.156614  0.184014   
1

In [6]:
df.shape

(1456, 24)

In [8]:
datadict = pd.DataFrame(df.dtypes)

In [9]:
datadict['Missing Values'] = df.isnull().sum()

In [10]:
datadict["Nunique"] = df.nunique()

In [11]:
datadict["Count"] = df.count()

In [12]:
datadict

0  Missing Values  Nunique  Count
city                                    object               0        2   1456
year                                     int64               0       21   1456
weekofyear                               int64               0       53   1456
week_start_date                         object               0     1049   1456
ndvi_ne                                float64             194     1214   1262
ndvi_nw                                float64              52     1365   1404
ndvi_se                                float64              22     1395   1434
ndvi_sw                                float64              22     1388   1434
precipitation_amt_mm                   float64              13     1157   1443
reanalysis_air_temp_k                  float64              10     1176   1446
reanalysis_avg_temp_k                  float64              10      600   1446
reanalysis_dew_point_temp_k            float64              10     1180   1446
reanalysis_max_air_temp_k              float64              10      141   1446
reanalysis_min_air_temp_k              float64              10      117   1446
reanalysis_precip_amt_kg_per_m2        float64              10     1039   1446
reanalysis_relative_humidity_percent   float64              10     1370   1446
reanalysis_sat_precip_amt_mm           float64              13     1157   1443
reanalysis_specific_humidity_g_per_kg  float64              10     1171   1446
reanalysis_tdtr_k                      float64              10      519   1446
station_avg_temp_c                     float64              43      492   1413
station_diur_temp_rng_c                float64              43      470   1413
station_max_temp_c                     float64              20       73   1436
station_min_temp_c                     float64              14       73   1442
station_precip_mm                      float64              22      663   1434

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
del df['week_start_date']

In [15]:
df

city  year  weekofyear   ndvi_ne   ndvi_nw   ndvi_se   ndvi_sw  \
0      sj  1990          18  0.122600  0.103725  0.198483  0.177617   
1      sj  1990          19  0.169900  0.142175  0.162357  0.155486   
2      sj  1990          20  0.032250  0.172967  0.157200  0.170843   
3      sj  1990          21  0.128633  0.245067  0.227557  0.235886   
4      sj  1990          22  0.196200  0.262200  0.251200  0.247340   
5      sj  1990          23       NaN  0.174850  0.254314  0.181743   
6      sj  1990          24  0.112900  0.092800  0.205071  0.210271   
7      sj  1990          25  0.072500  0.072500  0.151471  0.133029   
8      sj  1990          26  0.102450  0.146175  0.125571  0.123600   
9      sj  1990          27       NaN  0.121550  0.160683  0.202567   
10     sj  1990          28  0.192875  0.082350  0.191943  0.152929   
11     sj  1990          29  0.291600  0.211800  0.301200  0.280667   
12     sj  1990          30  0.150567  0.171700  0.226900  0.214557   
13     sj  1990          31       NaN  0.247150  0.379700  0.381357   
14     sj  1990          32       NaN  0.064333  0.164443  0.138857   
15     sj  1990          33       NaN  0.128033  0.206957  0.168243   
16     sj  1990          34  0.190233  0.168800  0.167657  0.172286   
17     sj  1990          35  0.252900  0.330750  0.264171  0.284314   
18     sj  1990          36  0.235400  0.200025  0.283817  0.230443   
19     sj  1990          37  0.127967  0.437100  0.123400  0.148283   
20     sj  1990          38  0.196350  0.182433  0.254829  0.305686   
21     sj  1990          39  0.116100  0.260900  0.199443  0.244217   
22     sj  1990          40  0.228550  0.189750  0.212486  0.201186   
23     sj  1990          41  0.171150  0.067550  0.179467  0.157717   
24     sj  1990          42       NaN  0.070200  0.181617  0.165750   
25     sj  1990          43  0.146200  0.089750  0.128829  0.123929   
26     sj  1990          44  0.252250  0.183433  0.318000  0.295900   
27     sj  1990          45  0.152600  0.181775  0.178329  0.186629   
28     sj  1990          46  0.290800  0.224600  0.180386  0.234886   
29     sj  1990          47  0.272200  0.330350  0.131633  0.125383   
...   ...   ...         ...       ...       ...       ...       ...   
1426   iq  2009          49  0.348529  0.290400  0.410614  0.370457   
1427   iq  2009          50  0.192200  0.193529  0.239886  0.285886   
1428   iq  2009          51  0.217600  0.240300  0.181771  0.262300   
1429   iq  2009          52  0.210422  0.257138  0.221133  0.300256   
1430   iq  2010          53       NaN       NaN       NaN       NaN   
1431   iq  2010           1  0.124571  0.179129  0.163843  0.135471   
1432   iq  2010           2  0.145286  0.142314  0.135300  0.167529   
1433   iq  2010           3  0.252114  0.230486  0.187329  0.302786   
1434   iq  2010           4  0.263271  0.230600  0.218871  0.261286   
1435   iq  2010           5  0.170100  0.142117  0.117914  0.139343   
1436   iq  2010           6  0.230757  0.189257  0.163486  0.238871   
1437   iq  2010           7  0.293300  0.247829  0.206629  0.266671   
1438   iq  2010           8  0.303657  0.260057  0.225486  0.333314   
1439   iq  2010           9  0.127317  0.181160  0.120467  0.142767   
1440   iq  2010          10  0.311729  0.292686  0.272586  0.394800   
1441   iq  2010          11  0.294600  0.250971  0.281471  0.341643   
1442   iq  2010          12  0.266286  0.301233  0.296000  0.295743   
1443   iq  2010          13  0.141433  0.204729  0.250971  0.145243   
1444   iq  2010          14  0.242843  0.272757  0.202271  0.260114   
1445   iq  2010          15  0.157686  0.156614  0.184014  0.135886   
1446   iq  2010          16  0.231486  0.294686  0.331657  0.244400   
1447   iq  2010          17  0.239743  0.259271  0.307786  0.307943   
1448   iq  2010          18  0.260814  0.255786  0.257771  0.340286   
1449   iq  2010          19  0.168686  0.158500  0.133071  0.145600   
1450   iq  2010          20  

In [16]:
X_train = df.iloc[:, :].values

In [17]:
type(X_train)

numpy.ndarray

In [18]:
from sklearn.preprocessing import Imputer

In [19]:
imputer = Imputer()

In [20]:
X_train[:,3:23] = imputer.fit_transform(X_train[:, 3:23])

In [21]:
X_train

array([['sj', 1990, 18, ..., 29.4, 20.0, 16.0],
       ['sj', 1990, 19, ..., 31.7, 22.2, 8.6],
       ['sj', 1990, 20, ..., 32.2, 22.8, 41.4],
       ...,
       ['iq', 2010, 23, ..., 32.2, 19.2, 7.4],
       ['iq', 2010, 24, ..., 31.2, 21.0, 16.0],
       ['iq', 2010, 25, ..., 33.7, 22.2, 20.4]], dtype=object)

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
encoder = LabelEncoder?

In [26]:
encoder = LabelEncoder()

In [28]:
X_train[:,0] = encoder.fit_transform(X_train[:,0])

In [29]:
X_train

array([[1, 1990, 18, ..., 29.4, 20.0, 16.0],
       [1, 1990, 19, ..., 31.7, 22.2, 8.6],
       [1, 1990, 20, ..., 32.2, 22.8, 41.4],
       ...,
       [0, 2010, 23, ..., 32.2, 19.2, 7.4],
       [0, 2010, 24, ..., 31.2, 21.0, 16.0],
       [0, 2010, 25, ..., 33.7, 22.2, 20.4]], dtype=object)

In [30]:
X_train

array([[1, 1990, 18, ..., 29.4, 20.0, 16.0],
       [1, 1990, 19, ..., 31.7, 22.2, 8.6],
       [1, 1990, 20, ..., 32.2, 22.8, 41.4],
       ...,
       [0, 2010, 23, ..., 32.2, 19.2, 7.4],
       [0, 2010, 24, ..., 31.2, 21.0, 16.0],
       [0, 2010, 25, ..., 33.7, 22.2, 20.4]], dtype=object)

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc = StandardScaler()

In [33]:
X_train = sc.fit_transform(X_train)

/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [34]:
X_train

array([[ 0.74535599, -2.04044804, -0.56635649, ..., -1.56926583,
        -1.34242291, -0.49547268],
       [ 0.74535599, -2.04044804, -0.49975322, ..., -0.38682995,
         0.06248668, -0.65265527],
       [ 0.74535599, -2.04044804, -0.43314995, ..., -0.12977867,
         0.44564384,  0.04404597],
       ...,
       [-1.34164079,  1.65883268, -0.23334015, ..., -0.12977867,
        -1.85329913, -0.67814434],
       [-1.34164079,  1.65883268, -0.16673689, ..., -0.64388123,
        -0.70382764, -0.49547268],
       [-1.34164079,  1.65883268, -0.10013362, ...,  0.64137516,
         0.06248668, -0.40201275]])

In [35]:
df2 = pd.read_csv("dengue_labels_train.csv")

In [36]:
df2

city  year  weekofyear  total_cases
0      sj  1990          18            4
1      sj  1990          19            5
2      sj  1990          20            4
3      sj  1990          21            3
4      sj  1990          22            6
5      sj  1990          23            2
6      sj  1990          24            4
7      sj  1990          25            5
8      sj  1990          26           10
9      sj  1990          27            6
10     sj  1990          28            8
11     sj  1990          29            2
12     sj  1990          30            6
13     sj  1990          31           17
14     sj  1990          32           23
15     sj  1990          33           13
16     sj  1990          34           21
17     sj  1990          35           28
18     sj  1990          36           24
19     sj  1990          37           20
20     sj  1990          38           40
21     sj  1990          39           27
22     sj  1990          40           42
23     sj  1990          41           33
24     sj  1990          42           43
25     sj  1990          43           37
26     sj  1990          44           57
27     sj  1990          45           71
28     sj  1990          46           44
29     sj  1990          47           56
...   ...   ...         ...          ...
1426   iq  2009          49            4
1427   iq  2009          50            4
1428   iq  2009          51            1
1429   iq  2009          52            0
1430   iq  2010          53            0
1431   iq  2010           1           10
1432   iq  2010           2            9
1433   iq  2010           3           17
1434   iq  2010           4           16
1435   iq  2010           5           11
1436   iq  2010           6           12
1437   iq  2010           7           19
1438   iq  2010           8           15
1439   iq  2010           9           12
1440   iq  2010          10           12
1441   iq  2010          11           16
1442   iq  2010          12            9
1443   iq  2010          13            4
1444   iq  2010          14            9
1445   iq  2010          15            6
1446   iq  2010          16            8
1447   iq  2010          17            4
1448   iq  2010          18            2
1449   iq  2010          19            7
1450   iq  2010          20            6
1451   iq  2010          21            5
1452   iq  2010          22            8
1453   iq  2010          23            1
1454   iq  2010          24            1
1455   iq  2010          25            4

[1456 rows x 4 columns]

In [39]:
y_train = df2.iloc[:,3].values

In [40]:
y_train

array([4, 5, 4, ..., 1, 1, 4])

In [43]:
np.savetxt("preprocessed_X_train.csv", X_train, delimiter=",")

In [44]:
np.savetxt("preprocessed_y_train.csv", y_train, delimiter=",")

In [45]:
from sklearn.linear_model import LinearRegression

In [46]:
regressor = LinearRegression()

In [47]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
X_train[1426]

array([-1.34164079,  1.47386864,  1.49834479,  1.57693226,  1.35699935,
        2.82270627,  2.02014619,  0.63647172,  0.04494687,  0.56497228,
        1.13246534,  1.69841127, -0.28139802,  2.178834  ,  1.33953278,
        0.63647172,  1.25272109,  0.80763374,  0.65941394,  1.1047218 ,
        1.46393924,  0.06248668,  0.20547674])

In [49]:
y_train[1426]

4

In [50]:
regressor.predict(X_train[1426:1427])

array([22.56691396])

In [52]:
y_train[718]

9

In [53]:
regressor.predict(X_train[718:719])

array([6.93781626])

In [54]:
from sklearn.decomposition import PCA

In [55]:
pca = PCA()

In [56]:
X_train = pca.fit_transform(X_train)

In [57]:
X_test = pca.transform(X_test)

NameError: name 'X_test' is not defined

In [58]:
df4 = pd.read_csv("dengue_features_test.csv")

In [59]:
df4

city  year  weekofyear week_start_date   ndvi_ne   ndvi_nw   ndvi_se  \
0     sj  2008          18      2008-04-29 -0.018900 -0.018900  0.102729   
1     sj  2008          19      2008-05-06 -0.018000 -0.012400  0.082043   
2     sj  2008          20      2008-05-13 -0.001500       NaN  0.151083   
3     sj  2008          21      2008-05-20       NaN -0.019867  0.124329   
4     sj  2008          22      2008-05-27  0.056800  0.039833  0.062267   
5     sj  2008          23      2008-06-03 -0.044000 -0.030467  0.132000   
6     sj  2008          24      2008-06-10 -0.044300 -0.024925  0.132271   
7     sj  2008          25      2008-06-17       NaN  0.082150  0.144371   
8     sj  2008          26      2008-06-24  0.010800  0.049900  0.100571   
9     sj  2008          27      2008-07-01  0.072667  0.106660  0.155429   
10    sj  2008          28      2008-07-08 -0.046450  0.006825  0.260286   
11    sj  2008          29      2008-07-15       NaN       NaN  0.195843   
12    sj  2008          30      2008-07-22  0.208300  0.429500  0.277683   
13    sj  2008          31      2008-07-29  0.000200  0.003900  0.109067   
14    sj  2008          32      2008-08-05  0.112200  0.032200  0.194186   
15    sj  2008          33      2008-08-12       NaN       NaN  0.058900   
16    sj  2008          34      2008-08-19  0.289150  0.241033  0.240600   
17    sj  2008          35      2008-08-26  0.113200       NaN  0.226083   
18    sj  2008          36      2008-09-02       NaN  0.017300  0.190417   
19    sj  2008          37      2008-09-09  0.361900  0.649000  0.146400   
20    sj  2008          38      2008-09-16  0.091375  0.164050  0.251667   
21    sj  2008          39      2008-09-23  0.079500  0.103675  0.282686   
22    sj  2008          40      2008-09-30 -0.137350  0.130950  0.271886   
23    sj  2008          41      2008-10-07  0.130600  0.089700  0.186086   
24    sj  2008          42      2008-10-14  0.183400  0.117550  0.152457   
25    sj  2008          43      2008-10-21  0.033250  0.074867  0.336314   
26    sj  2008          44      2008-10-28  0.083400  0.075700  0.073629   
27    sj  2008          45      2008-11-04 -0.094400 -0.004950  0.143800   
28    sj  2008          46      2008-11-11  0.101100  0.074000  0.237600   
29    sj  2008          47      2008-11-18       NaN  0.044000  0.221043   
..   ...   ...         ...             ...       ...       ...       ...   
386   iq  2012          48      2012-12-02  0.376286  0.388143  0.433229   
387   iq  2012          49      2012-12-09  0.367617  0.354980  0.325817   
388   iq  2012          50      2012-12-16  0.130650  0.265457  0.223043   
389   iq  2012          51      2012-12-23  0.256983  0.223471  0.233883   
390   iq  2013           1      2013-01-01  0.255829  0.268657  0.268414   
391   iq  2013           2      2013-01-08  0.188229  0.139143  0.252729   
392   iq  2013           3      2013-01-15  0.252200  0.184743  0.241700   
393   iq  2013           4      2013-01-22  0.183729  0.127057  0.165986   
394   iq  2013           5      2013-01-29  0.368857  0.375329  0.336871   
395   iq  2013           6      2013-02-05  0.274957  0.270914  0.293043   
396   iq  2013           7      2013-02-12  0.267029  0.190729  0.279186   
397   iq  2013           8      2013-02-19  0.297967  0.327750  0.244357   
398   iq  2013           9      2013-02-26  0.345517  0.346867  0.337117   
399   iq  2013          10      2013-03-05  0.295343  0.309857  0.254686   
400   iq  2013          11      2013-03-12  0.223671  0.119450  0.224800   
401   iq  2013          12      2013-03-19  0.231800  0.195583  0.204786   
402   iq  2013          13      2013-03-26  0.263429  0.210614  0.269414   
403   iq  2013          14      2013-04-02  0.223543  0.208543  0.239971   
404   iq  2013          15      2013-04-09  0.263200  0.237400  0.250143   
405   iq  2013          16      2013-04-16  0.309029  0.270267  0.235500   
406   iq  2013          17      2013-04-23  0.193314

In [61]:
del df4["week_start_date"]

In [67]:
X_test = df4.iloc[:,:].values

In [68]:
X_test[:,3:23] = imputer.fit_transform(X_test[:, 3:23])

In [69]:
X_test

array([['sj', 2008, 18, ..., 33.3, 21.7, 75.2],
       ['sj', 2008, 19, ..., 30.0, 22.2, 34.3],
       ['sj', 2008, 20, ..., 32.8, 22.8, 3.0],
       ...,
       ['iq', 2013, 24, ..., 32.6, 21.6, 93.2],
       ['iq', 2013, 25, ..., 32.2, 21.8, 34.1],
       ['iq', 2013, 26, ..., 32.6, 22.0, 14.9]], dtype=object)

In [70]:
from sklearn.preprocessing import LabelEncoder

In [71]:
X_test[:,0] = encoder.fit_transform(X_test[:, 0])

In [73]:
X_test

array([[1, 2008, 18, ..., 33.3, 21.7, 75.2],
       [1, 2008, 19, ..., 30.0, 22.2, 34.3],
       [1, 2008, 20, ..., 32.8, 22.8, 3.0],
       ...,
       [0, 2013, 24, ..., 32.6, 21.6, 93.2],
       [0, 2013, 25, ..., 32.2, 21.8, 34.1],
       [0, 2013, 26, ..., 32.6, 22.0, 14.9]], dtype=object)

In [74]:
X_train = sc.inverse_transform(X_train)

In [75]:
X_train

array([[-7.73228906e-01,  2.02001370e+03,  2.60899092e+01, ...,
         3.25992905e+01,  2.21211241e+01,  3.93263598e+01],
       [-4.95553647e-01,  2.00769261e+03,  2.26317693e+01, ...,
         3.24686196e+01,  2.20783686e+01,  3.93263598e+01],
       [-3.63778625e-01,  1.99964209e+03,  3.31506235e+01, ...,
         3.24286897e+01,  2.21327595e+01,  3.93263598e+01],
       ...,
       [ 1.71799150e+00,  2.01595098e+03,  5.10313193e+01, ...,
         3.23541714e+01,  2.21140043e+01,  3.93263598e+01],
       [ 2.23486243e+00,  2.01516688e+03,  4.48239009e+01, ...,
         3.23447213e+01,  2.21126197e+01,  3.93263598e+01],
       [ 2.54928665e+00,  2.00275840e+03,  1.56056806e+01, ...,
         3.24099101e+01,  2.21112187e+01,  3.93263598e+01]])

In [76]:
from sklearn.decomposition import PCA

In [77]:
pca = PCA()

In [78]:
X_train = pca.fit_transform(X_train)

In [79]:
X_test = pca.transform(X_test)

In [80]:
pca.explained_variance_ratio_

array([4.88877418e-01, 2.54885655e-01, 1.20959977e-01, 6.68869755e-02,
       6.28801404e-02, 2.14864471e-03, 9.50870198e-04, 7.65591724e-04,
       5.28145002e-04, 3.62548415e-04, 2.60824922e-04, 2.53157699e-04,
       1.52007430e-04, 3.86487982e-05, 1.41525358e-05, 1.19685068e-05,
       9.17637796e-06, 6.27451503e-06, 2.90860877e-06, 2.16167676e-06,
       2.01936950e-06, 7.33569467e-07, 4.57354562e-28])