In [0]:

import numpy as np
import pandas as pd

In [0]:
from google.colab import files

uploaded = files.upload()

Saving dengue_features_test.csv to dengue_features_test (2).csv
Saving dengue_features_train.csv to dengue_features_train (2).csv
Saving dengue_labels_train.csv to dengue_labels_train (2).csv


In [0]:
import io
training_features = pd.read_csv(io.BytesIO(uploaded['dengue_features_train.csv']))
training_label =pd.read_csv(io.BytesIO(uploaded['dengue_labels_train.csv']))
test_features = pd.read_csv(io.BytesIO(uploaded['dengue_features_test.csv']))


In [0]:
training_features.shape

(1456, 24)

In [0]:
training_label.shape

(1456, 4)

In [0]:
del training_features['week_start_date']
del training_label['year']
del training_label['weekofyear']
del test_features['week_start_date']

In [0]:
training_features['reanalysis_air_temp_k']=training_features['reanalysis_air_temp_k']-273.15
training_features['reanalysis_avg_temp_k']=training_features['reanalysis_avg_temp_k']-273.15
training_features['reanalysis_dew_point_temp_k']=training_features['reanalysis_dew_point_temp_k']-273.15
training_features['reanalysis_max_air_temp_k']=training_features['reanalysis_max_air_temp_k']-273.15
training_features['reanalysis_min_air_temp_k']=training_features['reanalysis_min_air_temp_k']-273.15

In [0]:
test_features['reanalysis_air_temp_k']=test_features['reanalysis_air_temp_k']-273.15
test_features['reanalysis_avg_temp_k']=test_features['reanalysis_avg_temp_k']-273.15
test_features['reanalysis_dew_point_temp_k']=test_features['reanalysis_dew_point_temp_k']-273.15
test_features['reanalysis_max_air_temp_k']=test_features['reanalysis_max_air_temp_k']-273.15
test_features['reanalysis_min_air_temp_k']=test_features['reanalysis_min_air_temp_k']-273.15

In [0]:
training_features = training_features.drop([training_features.index[139] , training_features.index[451],training_features.index[763] , training_features.index[1170] ,training_features.index[1430]])
training_label=training_label.drop([training_label.index[139] , training_label.index[451],training_label.index[763] , training_label.index[1170] ,training_label.index[1430]])

In [0]:
len(training_features[training_features['city'] == 'sj'])

933

In [0]:
len(test_features[test_features['city']=='sj'])

260

In [0]:
len(training_label[training_label['city']=='sj'])

933

In [0]:
del training_features['city']

In [0]:
del training_label['city']

In [0]:
del test_features['city']

In [0]:
sj_train=training_features.iloc[:933,:]
iq_train=training_features.iloc[933:,:]

In [0]:
sj_train.head()

year  weekofyear  ...  station_min_temp_c  station_precip_mm
0  1990          18  ...                20.0               16.0
1  1990          19  ...                22.2                8.6
2  1990          20  ...                22.8               41.4
3  1990          21  ...                23.3                4.0
4  1990          22  ...                23.9                5.8

[5 rows x 22 columns]

In [0]:

sj_label=training_label.iloc[:933,:]
iq_label=training_label.iloc[933:,:]

In [0]:

sj_test=test_features.iloc[:260,:]

In [0]:

iq_test=test_features.iloc[260:,:]

In [0]:

sj_train=sj_train.fillna(method='ffill')

In [0]:
sj_label=sj_label.fillna(method='ffill')

In [0]:
iq_train=iq_train.fillna(method='ffill')

In [0]:
iq_label=iq_label.fillna(method='ffill')

In [0]:
sj_test=sj_test.fillna(method='ffill')


In [0]:
iq_test.isnull().sum()

year                                      0
weekofyear                                0
ndvi_ne                                   0
ndvi_nw                                   0
ndvi_se                                   0
ndvi_sw                                   0
precipitation_amt_mm                      0
reanalysis_air_temp_k                     0
reanalysis_avg_temp_k                     0
reanalysis_dew_point_temp_k               0
reanalysis_max_air_temp_k                 0
reanalysis_min_air_temp_k                 0
reanalysis_precip_amt_kg_per_m2           0
reanalysis_relative_humidity_percent      0
reanalysis_sat_precip_amt_mm              0
reanalysis_specific_humidity_g_per_kg     0
reanalysis_tdtr_k                         0
station_avg_temp_c                       10
station_diur_temp_rng_c                  10
station_max_temp_c                        1
station_min_temp_c                        7
station_precip_mm                         3
dtype: int64

In [0]:
iq_test=iq_test.fillna(method='ffill')

In [0]:
sj_test.isnull().sum()

year                                     0
weekofyear                               0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

In [0]:
sj_train.isnull().sum()

year                                     0
weekofyear                               0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

In [0]:
iq_train.isnull().sum()

year                                     0
weekofyear                               0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:

scaler=MinMaxScaler()

In [0]:
sj_train=scaler.fit_transform(sj_train)

In [0]:

sj_test=scaler.fit_transform(sj_test)

In [0]:
iq_train=scaler.fit_transform(iq_train)

In [0]:
iq_test=scaler.fit_transform(iq_test)

In [0]:
sj_train

array([[0.00000000e+00, 3.33333333e-01, 5.87839715e-01, ...,
        3.03370787e-01, 2.82051282e-01, 5.23046747e-02],
       [0.00000000e+00, 3.52941176e-01, 6.40415717e-01, ...,
        5.61797753e-01, 5.64102564e-01, 2.81137627e-02],
       [0.00000000e+00, 3.72549020e-01, 4.87411771e-01, ...,
        6.17977528e-01, 6.41025641e-01, 1.35338346e-01],
       ...,
       [1.00000000e+00, 2.74509804e-01, 2.79052965e-01, ...,
        3.03370787e-01, 5.00000000e-01, 1.00359595e-01],
       [1.00000000e+00, 2.94117647e-01, 4.53565275e-01, ...,
        3.03370787e-01, 5.00000000e-01, 3.66132723e-02],
       [1.00000000e+00, 3.13725490e-01, 4.10437392e-01, ...,
        5.61797753e-01, 7.05128205e-01, 9.80712651e-04]])

In [0]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(sj_train,sj_label)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [0]:
pred = regressor.predict(sj_test)

In [0]:
pred

array([  8.5,   5.9,   5.5,  20.8,   6.5,   6. ,   5.3,  31.7,  32.5,
        17.6,  22.5,  17.7,  49.5,  66.4,  64.3,  56.1,  83.4,  95.6,
        80.9, 115.6, 116.3,  65.4, 131.2,  98.9,  74.3,  60.8,  42.6,
        75.3,  61.5,  61.7,  72.6,  71.8,  65. ,  68.6,  62.4,  36. ,
        52.7,  39.1,  32. ,  43.4,  31.6,  35.7,  28.3,  37.5,  26. ,
        21.8,  23.3,  23.7,  14.2,  19.7,  18.2,  20.1,  23.8,  17.1,
        20.5,  20.1,  25.3,  29.5,  23.7,  34.8,  38.7,  43.7,  50. ,
        45.8,  88.3, 139.5, 134.3, 169. , 164.1, 218.9, 212.1, 204.2,
       185.4, 211.1, 234.3, 187. , 213.6, 198.7, 230. , 153.6, 128. ,
       221.8, 160.7, 129.9, 101.4,  96.1,  80.4,  47.1,  28.1,  36.9,
        36.1,  47.3,  38.7,  28.5,  28.5,  20.6,  28.6,  21.2,  16.1,
        24.3,  10.6,  13. ,  11.4,   5.1,  14.2,  42. ,   5.8,   8.8,
        25.3,  41. ,  34.8,  57.3,  48.9,  44.5,  37.5,  42.7,  30.7,
        59.6,  68. ,  66.7, 156.6, 153.2, 156.3, 130.1, 142.5, 124.4,
        96.9, 115. ,

In [0]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(iq_train,iq_label)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [0]:
pred_y = regressor.predict(iq_test)

In [0]:
pred_y

array([ 5.4,  4.9,  4.8,  5.6,  3.3,  4.3,  7.4,  2.8,  3.6,  7.8,  3.4,
        2.4,  9.9,  7.3, 14.7,  9.2, 18.4,  8.5,  7.5, 19.1, 15. ,  9.2,
       19. ,  4.8, 38.6,  8.7, 22.6, 13.3, 20.4, 13.1, 14.1, 21.5, 20.1,
       12.3, 13.1, 18.7, 14. ,  9.3,  8. ,  8.4,  8.2,  6.6,  7.1,  5.8,
        6.6,  2.8,  3.5,  6.1,  2.2,  2.2,  4.7,  1.7,  3.9,  1. ,  2.1,
        3.8,  1.9,  4.8,  3.4,  1.9,  3.1,  2.6,  2.6,  3.9,  4.8,  5.5,
        9.6,  5.9, 21.2,  6.2, 17.7,  6.8, 15.9,  8.7,  4.3,  6.2, 33.5,
       38. ,  5.7, 15.7, 18.2, 16.8, 16.9, 13. , 16.2, 19.8, 11.7, 20.6,
       10.5,  4.6,  4.8,  6.3,  4.3,  6.5,  4.9,  8.9,  4.7,  2.2,  8.5,
        3. ,  4. ,  3.3,  6.4,  3.9,  4.5,  3.3,  5.8,  3.1,  5.5,  1.3,
        3.8,  4.1,  6. ,  4.4,  3.4,  5.8,  5.4,  7.4, 21.5,  8.6, 11.3,
        9.7,  4.2, 11.4, 17.4, 29.5,  7.7, 15. , 16.6,  8.2, 18.5, 19.5,
       17.3, 12.6, 24.9, 10.7, 11.8, 16.3, 16.6, 12.6,  9.9,  9.1,  6.7,
        7.1,  6.1,  8. ,  4.9,  4.7,  6.3,  4.4,  3

In [0]:
pred.shape

(260,)

In [0]:
pred_y.shape

(156,)